name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: testdb
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Wait for MySQL
      run: |
        until mysqladmin ping -h"127.0.0.1" --silent; do
          echo 'waiting for mysql to be connectable...'
          sleep 5
        done
    - name: Create Database and Tables
      run: |
        mysql -h 127.0.0.1 -uroot -proot -e "CREATE DATABASE IF NOT EXISTS testdb;"
        mysql -h 127.0.0.1 -uroot -proot testdb < schema.sql
    - name: Check for security vulnerabilities
      run: npm audit
    - name: Run Tests
      run: npm test
    - name: Build the app
      run: npm run build

